const assert=require('node:assert/strict');
const {createPhotoSchedule,nextPhotoRequest,photoUrls,deletePhotoHistory}=require('../src/utils/cameraPhotos');
const Session=require('../src/models/Session');const Exam=require('../src/models/Exam');
const storage=require('../src/services/storage');const Violation=require('../src/models/Violation');
require('../src/utils/auditLogger').logTeacherAction=async()=>{};
const router=require('../src/routes/sessions');
const handler=(path,method='post')=>router.stack.find(layer=>layer.route?.path===path&&layer.route.methods[method]).route.stack.at(-1).handle;
const response=()=>({statusCode:200,status(n){this.statusCode=n;return this},json(data){this.data=data;return this}});
let session,exam,saves=0,update;
Session.findById=async()=>session;Exam.findOne=async()=>exam;
Session.findOneAndUpdate=async(query,changes)=>{update={query,changes};return session;};
storage.save=async()=>{saves++;return {url:'/uploads/verification/new.jpg'}};
Violation.prototype.save=()=>{throw Error('Routine request must not create violation')};
const call=async(path,body={},method='post')=>{const res=response();await handler(path,method)({body,params:{sessionId:'000000000000000000000001'},app:{locals:{}},headers:{}},res);return res;};
(async()=>{
 const scope=await import('../../dashboard/src/utils/examScope.js');
 const exams=[{_id:'id-a',examCode:'EXAM-A',examId:'alias-a',status:'active'},{_id:'id-b',examCode:'EXAM-B',status:'active'},{examCode:'OLD',status:'completed'}];
 const sessions=[{examId:'exam-a'},{examId:'alias-a'},{examId:'EXAM-B'},{examId:''},{examId:'OLD'}];
 assert.equal(scope.scopedExams(exams,' exam-a ').length,1);assert.equal(scope.scopedSessions(sessions,exams,'id-a').length,2);assert.equal(scope.scopedSessions(sessions,exams,null).length,3);assert.equal(scope.scopedSessions(sessions,exams,'unknown').length,0);
 const schedule=createPhotoSchedule(0,90000,()=>.5);assert.equal(schedule.length,3);assert.deepEqual(schedule.map(x=>+x.dueAt),[15000,45000,75000]);assert.equal(new Set(schedule.map(x=>x.id)).size,3);assert.deepEqual(createPhotoSchedule(50,20),[]);
 assert.equal(nextPhotoRequest(schedule,14000),null);assert.equal(nextPhotoRequest(schedule,16000).id,schedule[0].id);schedule[0].completedAt=new Date();assert.equal(nextPhotoRequest(schedule,16000),null);
 const deleted=[];await deletePhotoHistory({cameraVerificationPhoto:'a',cameraPhotos:[{url:'a'},{url:'b'}]},{delete:async url=>deleted.push(url)});assert.deepEqual(deleted,['a','b']);
 session={_id:'000000000000000000000001',examId:'EXAM-A',status:'active',cameraPhotos:[],cameraPhotoRequests:[],consentGiven:true,photoScheduleCreated:true};exam={examType:'online',status:'active'};
 let res=await call('/:sessionId/request-camera-photo',{note:'Improve lighting'});assert.equal(res.statusCode,200);assert.equal(update.changes.$push.cameraPhotoRequests.source,'requested');assert.equal(update.changes.$set,undefined);
 res=await call('/:sessionId/request-camera-photo',{note:{}});assert.equal(res.statusCode,400);
 exam.examType='physical_lab';res=await call('/:sessionId/request-camera-photo');assert.equal(res.statusCode,400);exam.examType='online';session.status='completed';res=await call('/:sessionId/request-camera-photo');assert.equal(res.statusCode,409);session.status='active';
 Session.findOneAndUpdate=async()=>null;res=await call('/:sessionId/request-camera-photo');assert.equal(res.statusCode,409);Session.findOneAndUpdate=async(query,changes)=>{update={query,changes};return session;};
 const jpeg='data:image/jpeg;base64,/9j/2Q==';
 res=await call('/:sessionId/camera-verification',{photoBase64:'junk'});assert.equal(res.statusCode,400);assert.equal(saves,0);
 res=await call('/:sessionId/camera-verification',{photoBase64:jpeg,requestId:'unknown'});assert.equal(res.statusCode,400);assert.equal(saves,0);
 session.cameraPhotoRequests=[{id:'request',source:'scheduled',dueAt:new Date(0),completedAt:new Date()}];res=await call('/:sessionId/camera-verification',{photoBase64:jpeg,requestId:'request'});assert.equal(res.statusCode,200);assert.equal(saves,0);
 session.cameraPhotoRequests[0].completedAt=null;session.cameraVerificationPhoto='old';res=await call('/:sessionId/camera-verification',{photoBase64:jpeg,requestId:'request'});assert.equal(res.statusCode,200);assert.equal(update.changes.$push.cameraPhotos.$each.length,2);assert.equal(update.changes.$push.cameraPhotos.$each[1].source,'scheduled');assert.equal(update.changes.$set.cameraVerificationStatus,'pending');
 session.cameraPhotos=[{url:'old',status:'pending'}];res=await call('/:sessionId/camera-verification',{status:'verified',photoUrl:'stale'},'patch');assert.equal(res.statusCode,409);
 session.cameraVerificationStatus='verified';res=await call('/:sessionId/camera-verification',{status:'verified',photoUrl:'old'},'patch');assert.equal(res.statusCode,200);assert.equal(update.query.cameraVerificationPhoto,'old');assert.equal(update.changes.$set['cameraPhotos.$[photo].status'],'verified');
 session.cameraPhotos=[{_id:'old-photo',url:'historical',status:'pending'}];
 res=await call('/:sessionId/camera-verification',{status:'verified',photoUrl:'historical',historyPhotoId:'old-photo'},'patch');assert.equal(res.statusCode,200);assert.equal(update.changes.$set.cameraVerificationStatus,undefined);assert.equal(update.changes.$set['cameraPhotos.$[photo].status'],'verified');
 res=await call('/:sessionId/camera-verification',{status:'verified',photoUrl:'historical',historyPhotoId:'wrong-photo'},'patch');assert.equal(res.statusCode,404);
 session.cameraPhotoRequests=[];session.photoScheduleCreated=false;session.consentGiven=true;session.endTime=new Date(Date.now()+90000);
 exam.startedAt=new Date();exam.endTime=session.endTime;
 let initialized=0;
 Session.findOneAndUpdate=async(query,changes)=>{initialized++;assert.equal(query.photoScheduleCreated.$ne,true);assert.equal(changes.$push.cameraPhotoRequests.$each.length,3);session.photoScheduleCreated=true;session.cameraPhotoRequests=changes.$push.cameraPhotoRequests.$each;return session;};
 res=await call('/:sessionId/status',{},'get');assert.equal(res.statusCode,200);assert.equal(initialized,1);assert.equal(res.data.cameraPhotoRequest,null);
 res=await call('/:sessionId/status',{},'get');assert.equal(initialized,1);
 session.photoScheduleCreated=false;exam.examType='physical_lab';res=await call('/:sessionId/status',{},'get');assert.equal(initialized,1);assert.equal(res.data.cameraPhotoRequest,null);
 exam.examType='online';session.consentGiven=false;res=await call('/:sessionId/status',{},'get');assert.equal(initialized,1);
 console.log('PASS: two-exam isolation, aliases, completed-exam exclusion, randomized schedule, due/completed requests, photo cleanup, non-penalizing retakes, physical-lab/ended/duplicate rejection, history and stale-photo review. No real data or camera used.');
})().catch(err=>{console.error(err);process.exitCode=1});
