const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
assert.match(fs.readFileSync(path.join(__dirname, 'src/index.js'), 'utf8'), /app\.use\('\/verification', require\('\.\/routes\/verification'\)\)/);
process.env.EMAIL_TOKEN_SECRET = 'verification-test-only-secret';
process.env.JWT_SECRET = 'access-test-only-secret';
const Teacher = require('./src/models/Teacher');
const Audit = require('./src/models/AuthAuditLog');
const Refresh = require('./src/models/RefreshToken');
const bcrypt = require('bcrypt');
const mail = require('./src/services/mail');
const strategy = require('./src/services/verification');
const auth = require('./src/routes/auth');
const verification = require('./src/routes/verification');
const handler = (router, path) => router.stack.find(x => x.route?.path === path).route.stack.at(-1).handle;
const response = () => ({ statusCode: 200, status(n){this.statusCode=n;return this;},json(data){this.data=data;return this;},cookie(){return this;} });
async function call(router,path,body){const res=response();await handler(router,path)({body,headers:{},ip:'127.0.0.1'},res);return res;}
(async()=>{
 assert(Teacher.schema.indexes().some(([keys,options])=>keys.email===1&&options.unique));
 let saved, mails=0, cookies=0;
 Teacher.findOne = async query => {assert.equal(query.email,'teacher@example.com');return {email:query.email};};
 let res=await call(auth,'/signup',{name:'Test Teacher',email:' Teacher@Example.com ',password:'Password1'});
 assert.equal(res.statusCode,409);
 Teacher.findOne=async()=>null;
 bcrypt.hash=async()=> 'hash';
 Teacher.prototype.save=async function(){saved=this;return this;};
 Audit.create=async()=>{};
 mail.send=async()=>{mails++;return {success:true};};
 process.env.REQUIRE_EMAIL_VERIFICATION='true';
 res=await call(auth,'/signup',{name:'Test Teacher',email:'teacher@example.com',password:'Password1'});
 assert.equal(res.statusCode,201);assert.equal(res.data.verificationRequired,true);assert.equal(res.data.accessToken,undefined);assert.equal(mails,1);
 Teacher.prototype.save=async()=>{throw Object.assign(new Error('duplicate'),{code:11000});};
 res=await call(auth,'/signup',{name:'Test Teacher',email:'teacher@example.com',password:'Password1'});assert.equal(res.statusCode,409);
 Teacher.findOne=async()=>({passwordHash:'hash',emailVerified:false,emailVerificationRequired:true});bcrypt.compare=async()=>true;
 res=await call(auth,'/login',{email:'teacher@example.com',password:'Password1'});assert.equal(res.statusCode,403);
 Teacher.findOne=async()=>({passwordHash:'hash',emailVerified:false});
 res=await call(auth,'/login',{email:'teacher@example.com',password:'Password1'});assert.equal(res.statusCode,403);
 const policy = require('./src/utils/emailVerification');
 assert.equal(policy.needsVerification({emailVerified:false}),true);
 assert.equal(policy.needsVerification({emailVerified:false,emailVerificationRequired:false}),true);
 assert.equal(policy.needsVerification({emailVerified:true,emailVerificationRequired:true}),false);
 assert.equal(policy.needsVerification({emailVerified:false,emailVerificationRequired:true}),true);
 const challenge=await strategy.generateChallenge(saved._id,saved.email);
 assert.equal((await strategy.verifyChallenge('000000000000000000000001',challenge.payload)).valid,false);
 assert.equal((await strategy.verifyChallenge(undefined,'invalid')).valid,false);
 Teacher.findByIdAndUpdate=(id,update)=>({select:async()=>{assert.equal(id,saved._id.toString());assert.equal(update.emailVerified,true);return saved;}});
 res=await call(verification,'/confirm',{submittedValue:challenge.payload});assert.equal(res.data.verified,true);
 res=await call(verification,'/send',{email:{}});assert.equal(res.statusCode,400);
 Teacher.findOne=async()=>null;Teacher.prototype.save=async function(){return this;};Refresh.create=async()=>{};
 process.env.REQUIRE_EMAIL_VERIFICATION='false';
 res=await call(auth,'/signup',{name:'Test Teacher',email:'teacher@example.com',password:'Password1'});assert.equal(res.statusCode,201);assert(res.data.accessToken);assert.equal(mails,1);
 console.log('PASS: normalized duplicate email, unique index declaration, concurrent duplicate, verification signup/login, token account binding, confirmation, invalid input and flag-off signup. No database or emails used.');
})().catch(err=>{console.error(err);process.exitCode=1;});
